title: Greg Vaughn's Musings
description: Mostly technical, primarily Elixir contents, but maybe I'll branch out too
author: Greg Vaughn
show_downloads: false
theme: jekyll-theme-architect

plugins:
  - jekyll-feed

# This below is supposed to let us avoid setting layout, but not sure its working
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
